### ISSUE TITLE
can't get past project config validation in latest

### ISSUE THREAD

**Issue by unwinder** [atsid/generator-ats-node-webapp#120]
Project config was working in previous versions but no longer.  Thought it might be related to defaults so provided a value for each field but still failed:

Error: Could not accept input [{"description":"a","homepage":"b","githubAccount":"c","authorName":"d","authorEmail":"e","authorUrl":"f","keywords":["g"]}], default=react
    at acceptString (/home/bryan/.npm-packages/lib/node_modules/generator-ats-node-webapp/generators/app/phases/prompting.js:16:11)
    at Object._default (/home/bryan/.npm-packages/lib/node_modules/generator-ats-node-webapp/generators/app/phases/prompting.js:94:16)
    at module.exports (/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/run-async/index.js:15:21)
    at Object.<anonymous> (/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/utils/utils.js:42:5)
    at module.exports (/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe](/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5755:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/home/bryan/.npm-packages/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1604:19)

**Comment by darthtrevino** [comment]
Hey Bryan,
It looks like when I added sequelize support, it broke some of the prompting. I've been working on build fixes today for various issues (e.g. library drift); I should have a good version out in a few minutes. I'll ping you

**Comment by darthtrevino** [comment]
@unwinder I just pushed a new version out. Can you try again with 0.11.4? This one has been e2e tested on Linux and OSX.

`npm install -g generator-ats-node-webapp@0.11.4`

**Comment by unwinder** [comment]
Seems to work fine now.  Thanks.
